version: '3.8'
services:
  db:
    container_name: db
    image: postgres:15.1-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - 5555:5432
    restart: always
volumes:
  data: